== Purpose

This project provides a RH-PAM KieServer embedded in SpringBoot.
It includes a pre-configured _KIE Container_ that manages the _mortgages_ KIE jar.

The resultant _Kie Container_  is then packaged into an immutable Linux container.

== Build

NOTE: The following commands make use of _podman_, _buildah_ and _podman_compose_.  The equivalent _docker_ family of utilities should also work.

=== KJars

. Build _mortgage_ app with rules
+
-----
-----

. Build _handling-wih-exception_ 
+
-----
-----

==== SpringBoot KIE-Server

. Build and start SpringBoot based KIE-Server app : 
+
-----
$ mvn clean package -DskipTests && \
         java -Dorg.kie.server.repo=etc/rhpam/runtime_configs \
              -jar target/rhpam-springboot-0.0.1.jar
-----

. Build linux container with KIE-Server:
+
-----
$ buildah bud -f docker/rhpam-springboot/Dockerfile \
              -t quay.io/redhat_naps_da/rhpam-springboot:0.0.2 
              .
-----

. Start pod with _postgresql_ and _rhpam-springboot_ linux containers:
+
-----
$ docker-compose -f etc/docker-compose.yaml up -d
-----

== Test


. Health Check Report
+
-----
$ curl -u "kieserver:kieserver" -H 'Accept:application/json' localhost:8080/rest/server/healthcheck?report=true
-----

. View swagger
+
-----
$ curl -v -u "kieserver:kieserver" localhost:8080/rest/swagger.json | jq .
-----

. List KIE Containers
+
-----
$ curl -u "kieserver:kieserver" -X GET http://localhost:8080/rest/server/containers
-----

. List process definitions in JSON representation:
+
-----
$ curl -u "kieserver:kieserver" -X GET -H 'Accept:application/json' localhost:8080/rest/server/containers/handling-wih-exception/processes/
-----

. Start a business process that throws a ProcessWIHException that delegates to a subprocess with human task
+
-----
$ curl -v -X POST -H 'Content-type:application/json' \
        localhost:8080/rest/server/containers/handling-wih-exception/processes/handling_wih_exception.MainProcess/instances \
        -d "{\"input\":\"HT\"}"

$ curl -X GET -H 'Accpet:application/json' localhost:8080/rest/server/queries/tasks/instances/process/{processInstanceId_of_subprocess}
-----


. Start and Signal ExecutorSample business process
+
-----
# select status, commandname, deploymentid, executions, message, processinstanceid, timestamp from requestinfo;

$ curl -v -X POST -H 'Content-type:application/json'         localhost:8080/rest/server/containers/handling-wih-exception/processes/ExecutorSample/instances
$ curl -v -X POST -H 'Content-type:application/json'         localhost:8080/rest/server/containers/handling-wih-exception/processes/SimpleSignal/instances

$ curl -v -X GET localhost:8080/rest/server/containers/handling-wih-exception/processes/instances/1/signals

$ curl -v -X POST -H 'Content-type:application/json' \
        localhost:8080/rest/server/containers/handling-wih-exception/processes/instances/1/signal/testSignal
-----

. Start a business process that throws a ProcessWIHException that retries a subprocess with timer 
+
-----
$ curl -v -X POST -H 'Content-type:application/json' \
        localhost:8080/rest/server/containers/handling-wih-exception/processes/handling_wih_exception.MainProcess/instances \
        -d "{\"input\":\"TIMER\"}"
-----

. Start a business process that throws a WorkItemHandlerRuntimeException that is caught by an Intermediary Catch Event
+
-----
$ curl -v -X POST -H 'Content-type:application/json' \
        localhost:8080/rest/server/containers/handling-wih-exception/processes/handling_wih_exception.BoundaryEventExceptionHandling/instances

-----

. Start a business process and return process variables:
+
-----
$ curl -X POST "localhost:8080/custom/processes/startAndReturnVars?correlationKey=rht&input=HT" | jq .
-----



. Test Drools API

.. Create a request payload that will be used when firing rules of the Mortgage sample application:
+
-----
$ echo '
{
  "commands": [
      { "insert": {
        "object": {
          "mortgages.mortgages.Applicant": {
            "name": "sarah",
            "age": 25,
            "creditRating": 650
          }
        },
        "out-identifier": "applicant_sarah",
        "return-object": true
      }},
      { "insert": {
        "object": {
          "mortgages.mortgages.LoanApplication": {
            "amount": 2500
          }
        },
        "out-identifier": "loanapp",
        "return-object": true
      }},
      { "insert": {
        "object": {
          "mortgages.mortgages.IncomeSource": {
            "amount": "50"
          }
        },
        "out-identifier": "incomesource",
        "return-object": true
      }},
      { "insert": {
        "object": {
          "mortgages.mortgages.Bankruptcy": {
            "yearOfOccurence": "1991",
            "amountOwed": "11000"
          }
        },
        "out-identifier": "bankruptcy",
        "return-object": true
      }},
    {
      "fire-all-rules": {
        "max": 10,
        "out-identifier": "firedActivations"
      }
    }
  ]
}

' > /tmp/mortgage_rules_execution.json
-----

.. Invoke kie-server with payload to insert facts and fire all rules of the Mortgage application:
+
-----
curl -v \
    -H  "accept: application/json" \
    -H  "content-type: application/json" \
    -X POST http://localhost:8080/rest/server/containers/instances/mortgages-0.0.1 \
    -d @/tmp/mortgage_rules_execution.json
-----

.. The response should include a JSON element that indicates that the loan application has been declined due to a prior bankruptcy:
+
-----
{
  "type" : "SUCCESS",
  "msg" : "Container mortgages_1.0.0 successfully called.",
  "result" : {
    "execution-results" : {
      "results" : [ {
        "value" : {"mortgages.mortgages.LoanApplication":{
  "amount" : 2500,
  "approved" : false,
  "approvedRate" : null,
  "deposit" : null,
  "explanation" : "has been bankrupt",
  "insuranceCost" : null,
  "lengthYears" : null
}}
-----


podman exec -it etc_dbuilder_runtime_1 /bin/sh

./wildfly/bin/jboss-cli.sh --connect --controller=localhost:10190
    /subsystem=logging/root-logger=ROOT:write-attribute(name=level, value=DEBUG)
    /subsystem=logging/console-handler=CONSOLE:write-attribute(name=level, value=DEBUG)
